### ISSUE TITLE
MiLight RGBW shows only color temperature in Homekit

### ISSUE THREAD

**Issue by eelco2k** [sprut666666/com.sprut.homekit#1]
I'm having problems showing the color wheel in Homekit for my RGBW LED strip.

I can only change the temperature (yellowish to white)

`TV Meubel full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"d6f3eee2-9bde-4bde-8f7a-9c3f0e647642","name":"TV Meubel","driver":{"uri":"homey:app:com.milight","id":"rgbw_bulb","path":"/opt/user/apps/3c59b2a681d5ce313739dea3230c3cc5/drivers/rgbw_bulb","assetsPath":"/app/com.milight/drivers/rgbw_bulb/assets/","wwwPath":"/app/com.milight/","owner_name":"Milight (EasyBulb)","owner_icon":"/app/com.milight/assets/icon.svg","virtual":false,"metadata":{"name":{"en":"RGBW Bulb","nl":"RGBW Lamp"},"class":"light","capabilities":["onoff","dim","light_hue","light_temperature","light_mode"],"capabilitiesOptions":{"onoff":{"setOnDim":false}},"icon":"/app/com.milight/drivers/rgbw_bulb/assets/icon.svg","settings":[{"id":"invert_red_and_green","type":"checkbox","value":false,"label":{"en":"Invert red and green values","nl":"Wissel rode en groene waarden om"},"hint":{"en":"Some Milight lights have the red and green values switched. If Homey sets a different color on your light than expected, enable this setting.","nl":"Sommige Milight lampen hebben de rode en groene waarden omgedraait. Als Homey een andere kleur instelt op de lamp dan verwacht, vink dan deze checkbox aan."}},{"id":"hue_calibration","type":"number","value":0,"attr":{"min":-0.5,"max":0.5,"step":0.01},"label":{"en":"Hue calibration","nl":"Kleur tint kalibratie"},"hint":{"en":"Use this value to calibrate the hue value send to the device. This can be used to compensate for deviating colors.","nl":"Gebruik deze waarde om de kleur tint te kalibreren. Dit kan gebruikt worden om te compenseren voor afwijkende kleuren."}}],"pair":true,"unpair":false,"repair":false},"ready":true},"zone":{"id":"9919ee1e-ffbc-480b-bc4b-77fb047e9e68","name":"Thuis","icon":"home","index":1,"parent":false},"data":{"id":"AC:CA:23:46:70:195RGBW","bridgeMacAddress":"AC:CA:23:46:70:19","zoneNumber":1,"driverType":"RGBW"},"icon":"/app/com.milight/drivers/rgbw_bulb/assets/icon.svg","settings":{"invert_red_and_green":true,"hue_calibration":0.34},"class":"light","capabilities":{"onoff":{"uri":"homey:manager:devices","id":"onoff","type":"boolean","title":{"en":"Turned on","nl":"Aangezet"},"getable":true,"setable":true,"options":{"setOnDim":{"type":"boolean","default":true,"desc":{"en":"When a device has both an `onoff` and `dim` capability, and Homey wants to turn the device on AND to a specific dim value, set this capability to `false` to prevent Homey from sending a set command."}},"greyout":{"type":"boolean","default":false,"desc":{"en":"When this capability is false, give a visual hint to greyout the device."}}}},"dim":{"uri":"homey:manager:devices","id":"dim","type":"number","title":{"en":"Dim level","nl":"Dim niveau"},"chartType":"stepLine","min":0,"max":1,"decimals":2,"getable":true,"setable":true},"light_hue":{"uri":"homey:manager:devices","id":"light_hue","type":"number","title":{"en":"Hue","nl":"Hue"},"min":0,"chartType":"stepLine","max":1,"decimals":2,"getable":true,"setable":true},"light_temperature":{"uri":"homey:manager:devices","id":"light_temperature","type":"number","title":{"en":"Temperature","nl":"Kleurtemperatuur"},"min":0,"chartType":"stepLine","max":1,"decimals":2,"getable":true,"setable":true},"light_mode":{"uri":"homey:manager:devices","id":"light_mode","type":"enum","title":{"en":"Light mode","nl":"Lamp modus"},"desc":{"en":"Switch between Color or Temperature mode","nl":"Schakel tussen Kleur of Temperatuur modus"},"values":[{"id":"color","title":{"en":"Color","nl":"Kleur"}},{"id":"temperature","title":{"en":"Temperature","nl":"Temperatuur"}}],"getable":true,"setable":true}},"capabilitiesArray":["onoff","dim","light_hue","light_temperature","light_mode"],"capabilitiesOptions":{"onoff":{"setOnDim":false},"dim":{},"light_hue":{},"light_temperature":{},"light_mode":{}},"flags":[],"mobile":{"components":[{"id":"icon","capabilities":["onoff"]},{"id":"slider","capabilities":["dim"]},{"id":"color","capabilities":["light_hue","light_temperature","light_mode"]}]},"order":16,"online":true,"state":{"onoff":false,"dim":1,"light_hue":0.07,"light_temperature":null,"light_mode":"temperature"},"lastUpdated":{"onoff":"2017-10-04T19:17:16.510Z","dim":"2017-10-04T19:15:24.098Z","light_hue":"2017-10-04T15:41:02.890Z","light_temperature":"2017-10-03T20:01:27.199Z","light_mode":"2017-10-04T19:15:15.487Z"},"available":true}`

`Realtime event from: TV Meubel. Value: {"onoff":true,"dim":1,"light_hue":0.07,"light_temperature":null,"light_mode":"temperature"}`

`TV Meubel: set light_temperature = null => 0.68`

**Comment by eelco2k** [comment]
When using the Elgato Eve app (https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8)
I can change the color with the color wheel....

**Comment by sprut666666** [comment]
Update 1.1.5 & check

**Comment by eelco2k** [comment]
yes works perfectly! Thank you for fast response!
