### ISSUE TITLE
Suddenlly homey devices stop responding from homekit

### ISSUE THREAD

**Issue by mbaghdas** [sprut666666/com.sprut.homekit#10]
Hello, 
i did install homekit app in my homey before a week, everything was working as suppose to be till yesterday, all the devices stop responding from apple homekit. 
thank you

**Comment by muaki** [comment]
Happens to me every time homekit app gets updated.

**Comment by sprut666666** [comment]
How does it work with version 1.3.2?

**Comment by mbaghdas** [comment]
i did delete and re install the latest 1.3.2 yesterday and agian today im getting homey xxxxxx  This accessory is not responding

**Comment by sprut666666** [comment]
very strange, which devices are added? under what conditions is this happening?

**Comment by mbaghdas** [comment]
The problem is homekit cant find the homey bridge so all the other davices will los the connection. i fell its when i leave the house and come back. its something to do with reconnecting with the wifi.

**Comment by mbaghdas** [comment]
I think the problem is when my phone is connect to wifi 5Hz and homey is on 2.5Hz. but why is that , they still have the same ip rang?

**Comment by sprut666666** [comment]
This should not be a problem, initially they work like this?

**Comment by mbaghdas** [comment]
no i feel it was after 1.3.1 release or after apple did update the homekit last week.

**Comment by mbaghdas** [comment]
i will try to do some test  cases becuase after apple update i could invite and share my homekit with my wife, maybe that will be an issue. i will test some diffreent scenario and let you know.

**Comment by sprut666666** [comment]
Thanks, but be sure to use 1.3.2

**Comment by Veldkornet** [comment]
I have the same problem. From Home on my iPhone, it says that the device is not responding. 
Then I need to restart the HomeKit app on Homey, and then everything work okay again for a day or two. 

In general, it happens to me at least 1-2 times per week.

**Comment by sprut666666** [comment]
=> https://github.com/sprut666666/com.sprut.homekit/issues/9
