### ISSUE TITLE
does not show temperature below 0 degrees

### ISSUE THREAD

**Issue by Turtures** [sprut666666/com.sprut.homekit#12]
homeKit can not display temperatures below 0 degrees, it stops at 0 degrees even if it is -9 degrees. Homey shows the correct temperature of the thermometers

**Comment by sprut666666** [comment]
next update

**Comment by sprut666666** [comment]
Should be fixed in 1.5.0

**Comment by Turtures** [comment]
Hello can you fix this.  homekit now shows minus degrees, but
siri can not read that it is - degrees

Med vänliga hälsningar!
Tom Danielsson
