### ISSUE TITLE
Cant add Fibaro devices after update 

### ISSUE THREAD

**Issue by Patrikgolfer** [sprut666666/com.sprut.homekit#15]
#When adding all my fibaro devices i get error message 
Its the same for my Fibaro doubletswitch2 and dimmer 2  
in log its like this for an Fibaro wallplug https://www.fibaro.com/en/products/wall-plug/

Kamin full info: {"__athom_api_type":"HomeyAPI.ManagerDevices.Device","id":"dfdd64f2-48cd-402c-8805-0e338568ee38","name":"Kamin","driver":{"uri":"homey:app:com.fibaro","id":"FGWPx-102-PLUS","path":"/opt/user/apps/f994092daee7a05ed59314f8c8ec8dcb/drivers/FGWPx-102-PLUS","assetsPath":"/app/com.fibaro/drivers/FGWPx-102-PLUS/assets/","wwwPath":"/app/com.fibaro/","owner_name":"Fibaro","owner_icon":"/app/com.fibaro/assets/icon.svg","virtual":false,"metadata":{"name":{"en":"Wall Plug (Z-Wave Plus)","nl":"Tussenstekker (Z-Wave Plus)"},"class":"socket","capabilities":["onoff","measure_power","meter_power"],"icon":"/app/com.fibaro/drivers/FGWPx-102-PLUS/assets/icon.svg","settings":[{"type":"group","label":"Device Specific","children":[{"id":"always_on","type":"checkbox","label":{"en":"Always on","nl":"Altijd aan"},"value":false,"hint":{"en":"Once activated, will keep a connected device constantly on, will stop reacting to alarm frames and B-button push","nl":"Wanneer geactiveerd zal de plug constant aan zijn, en niet meer reageren op de B-knop en alarm frames"}},{"id":"save_state","type":"checkbox","label":{"en":"Save Power-off State","nl":"Onthoud Stroom-eraf Status"},"hint":{"en":"Saves its last state when power is disconnected","nl":"Onthoud zijn laatste status wanneer stroom eraf word gehaald"},"value":true},{"id":"immediate_watt_percent_report","type":"number","label":{"en":"Watt Report","nl":"Watt Verzending"},"hint":{"en":"How much must the Wattage have changed (in percentage) before the value is being send immediatly. Range: 1 - 99, 100 = Not used","nl":"Hoeveel moet de Wattage zijn veranderd (in percentage) voor de waarde meteen word verzonden. Bereik: 1 - 99, 100 = Niet gebruikt"},"attr":{"min":1,"max":100},"value":80},{"id":"watt_threshold_report","type":"number","label":{"en":"Watt Report Threshold","nl":"Watt Verzending Drempel"},"hint":{"en":"How much must the Wattage at least have changed (in percentage) before the value is being send on the interval. Range: 1 - 99, 100 = Not used","nl":"Hoeveel moet de Wattage minimaal zijn veranderd (in percentage) voor de waarde word verzonden op het interval. Bereik: 1 - 99, 100 = Niet gebruikt"},"attr":{"min":1,"max":100},"value":15},{"id":"watt_interval_report","type":"number","label":{"en":"Watt Report Interval","nl":"Watt Verzending Interval"},"hint":{"en":"Set the interval (in seconds) that the Wattage is being send, if change is more then the specified threshold. Range: 5 - 600","nl":"Zet op welk interval (in seconden) het vermogen word verzonden, als de waarde meer veranderd is dan de drempel. Bereik: 5 - 600"},"attr":{"min":5,"max":600},"value":30},{"id":"kwh_threshold_report","type":"number","label":{"en":"kWh Report Threshold","nl":"kWh Verzending Drempel"},"hint":{"en":"How much must the kWh at least have changed before the value is being send. Range: 0.01 - 5, 0 = Not send","nl":"Hoeveel moet de kWh minimaal zijn veranderd voor de waarde word verzonden. Bereik: 0.01 - 5, 0 = Niet verzonden"},"attr":{"min":0,"max":5,"step":0.01},"value":0.1},{"id":"watt_kwh_report_interval","type":"number","label":{"en":"All Report Interval","nl":"Alles Verzending Interval"},"hint":{"en":"How often will the Watt and kWh be send (in seconds), even when threshold and interval are not met. Range: 5 - 32400, 0 = Not send","nl":"Hoe vaak word de Watt en kWh verzonden (in seconden), ook als de drempel en interval niet bereikt zijn. Bereik: 5 - 32400, 0 = Niet verzonden"},"attr":{"min":0,"max":32400},"value":3600},{"id":"own_power","type":"checkbox","label":{"en":"Include own power consumption","nl":"inclusief eigen verbruik"},"hint":{"en":"Does the power consumption (kWh) of the module itself be added on the total amount?","nl":"Moet het energie verbruik (kWh) van de module zelf opgeteld worden bij de totale hoeveelheid?"},"value":false},{"id":"control_onoff_group2","type":"dropdown","label":{"en":"Control association group 2","nl":"Controlle associatie groep 2"},"value":"0","hint":{"en":"What will devices do, that are specified in association group 2, when pressing the b-button","nl":"Wat doen apparaten, die gespecificeerd zijn in associatie groep 2, wanneer je op de b-knop drukt"},"values":[{"id":"0","label":{"en":"Wallplug off, device(s) also off. Wallplug on, device(s) also on","nl":"Muurplug uit, apparaat(en) ook uit. Muurplug aan, apparaat(en) ook aan"}},{"id":"1","label":{"en":"Wallplug off, device(s) on. Wallplug on, device(s) off","nl":"Muurplug uit, apparaat(en) aan. Muurplug aan, apparaat(en) uit"}}]},{"id":"led_ring_color_on","type":"dropdown","label":{"en":"Color when on","nl":"Kleur wanneer aan"},"value":"1","hint":{"en":"Defines the color of the LED ring in on state","nl":"De kleur van de LED ring wanneer aan"},"values":[{"id":"1","label":{"en":"Changes in predefined steps according to power load","nl":"Verandert in stappen afhankelijk van het stroom verbuik"}},{"id":"2","label":{"en":"Changes continuously according to power load using full spectrum of LED color","nl":"Verandert continu afhankelijk van het stroom verbruik"}},{"id":"3","label":{"en":"White","nl":"Wit"}},{"id":"4","label":{"en":"Red","nl":"Rood"}},{"id":"5","label":{"en":"Green","nl":"Groen"}},{"id":"6","label":{"en":"Blue","nl":"Blauw"}},{"id":"7","label":{"en":"Yellow","nl":"Geel"}},{"id":"8","label":{"en":"Cyan","nl":"Cyaan"}},{"id":"9","label":{"en":"Magenta","nl":"Magenta"}},{"id":"0","label":{"en":"Off","nl":"Uit"}}]},{"id":"led_ring_color_off","type":"dropdown","label":{"en":"Color when off","nl":"Kleur wanneer uit"},"value":"1","hint":{"en":"Defines the color of the LED ring in off state","nl":"Kleur van de LED ring wanneer uit"},"values":[{"id":"1","label":{"en":"LED ring is illuminated with a color corresponding to the last measured power, before the controlled device was turned off","nl":"LED ring is verlicht met een kleur die bij het laatst gemeten stroom verbruik hoort"}},{"id":"3","label":{"en":"White","nl":"Wit"}},{"id":"4","label":{"en":"Red","nl":"Rood"}},{"id":"5","label":{"en":"Green","nl":"Groen"}},{"id":"6","label":{"en":"Blue","nl":"Blauw"}},{"id":"7","label":{"en":"Yellow","nl":"Geel"}},{"id":"8","label":{"en":"Cyan","nl":"Cyaan"}},{"id":"9","label":{"en":"Magenta","nl":"Magenta"}},{"id":"0","label":{"en":"Off","nl":"Uit"}}]}]},{"type":"group","label":"Associations","collapsed":true,"children":[{"id":"zw_group_1","type":"text","value":"","hint":"This group supports 1 other devices to make an association to.\n\nSend to MultiChannel nodes by seperating with a dot, e.g. '3.4' to target subnode 4 of node 3.","label":"Group 1","pattern":"^(([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))?(,([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))?){0,0})?$"},{"id":"zw_group_2","type":"text","value":"","hint":"This group supports 10 other devices to make an association to.\n\nSend to MultiChannel nodes by seperating with a dot, e.g. '3.4' to target subnode 4 of node 3.","label":"Group 2","pattern":"^(([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))?(,([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))?){0,9})?$"},{"id":"zw_group_3","type":"text","value":"","hint":"This group supports 10 other devices to make an association to.\n\nSend to MultiChannel nodes by seperating with a dot, e.g. '3.4' to target subnode 4 of node 3.","label":"Group 3","pattern":"^(([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))?(,([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(.([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]))?){0,9})?$"}]},{"type":"group","label":"Raw Configuration Parameters","description":"Note: when using this field, any device specific values might become out of sync.","collapsed":true,"children":[{"id":"zw_configuration_value","type":"text","value":"","label":"Value","attr":{"placeholder":"id, size, value; id, size, value; ..."},"pattern":"^(([1-9]|1?[0-9][0-9]|2[0-4][0-9]|25[0-5])\\,([1,2,4])\\,(\\d+|0x[0-9a-fA-F]+)\\;?)+$"}]},{"type":"group","label":"Node Information","collapsed":true,"children":[{"id":"zw_node_id","type":"label","value":"","label":"Node ID"},{"id":"zw_secure","type":"label","value":"","label":"Secure"},{"id":"zw_battery","type":"label","value":"","label":"Battery"},{"id":"zw_manufacturer_id","type":"label","value":"","label":"Manufacturer ID"},{"id":"zw_product_type_id","type":"label","value":"","label":"Product Type ID"},{"id":"zw_product_id","type":"label","value":"","label":"Product ID"},{"id":"zw_firmware_id","type":"label","value":"","label":"Firmware version"},{"id":"zw_device_class_basic","type":"label","value":"","label":"Device Class (Basic)"},{"id":"zw_device_class_generic","type":"label","value":"","label":"Device Class (Generic)"},{"id":"zw_device_class_specific","type":"label","value":"","label":"Device Class (Specific)"}]}],"zwave":{"manufacturerId":271,"productTypeId":1538,"productId":[4097,8193,12289],"learnmode":{"image":"/drivers/FGWPx-102-PLUS/assets/learnmode.svg","instruction":{"en":"Insert the Wall Plug in a socket or press the button on your Fibaro Wall Plug three times","nl":"Stop de Tussenstekker in het stopcontact of druk driemaal op de knop op de Tussenstekker"}},"associationGroups":[1]},"pair":false,"unpair":false,"repair":false},"ready":true},"zone":{"id":"855113f1-f488-4223-b675-2f01270f573e","name":"Uterummet","icon":"default","index":7,"parent":"9919ee1e-ffbc-480b-bc4b-77fb047e9e68"},"data":{"token":"8c87fa9c-702f-421f-9b4d-e712ec6ceb68"},"icon":"/app/com.fibaro/drivers/FGWPx-102-PLUS/assets/icon.svg","settings":{"always_on":false,"save_state":true,"immediate_watt_percent_report":80,"watt_threshold_report":15,"watt_interval_report":30,"kwh_threshold_report":0.1,"watt_kwh_report_interval":3600,"own_power":false,"control_onoff_group2":"0","led_ring_color_on":"1","led_ring_color_off":"1","zw_node_id":"15","zw_manufacturer_id":"271","zw_product_type_id":"1538","zw_product_id":"4097","zw_secure":"manager.vdevice.drivers.zwavebasic.devicesettings.yes_true","zw_battery":"manager.vdevice.drivers.zwavebasic.devicesettings.yes_false","zw_device_class_basic":"BASIC_TYPE_ROUTING_SLAVE","zw_device_class_generic":"GENERIC_TYPE_SWITCH_BINARY","zw_device_class_specific":"SPECIFIC_TYPE_POWER_SWITCH_BINARY","zw_wakeup_interval":0,"zw_group_1":"1","zw_group_2":"","zw_group_3":""},"class":"socket","capabilities":{"onoff":{"uri":"homey:manager:devices","id":"onoff","type":"boolean","title":{"en":"Turned on","nl":"Aangezet"},"getable":true,"setable":true,"options":{"setOnDim":{"type":"boolean","default":true,"desc":{"en":"When a device has both an `onoff` and `dim` capability, and Homey wants to turn the device on AND to a specific dim value, set this capability to `false` to prevent Homey from sending a set command."}},"greyout":{"type":"boolean","default":false,"desc":{"en":"When this capability is false, give a visual hint to greyout the device."}}}},"measure_power":{"uri":"homey:manager:devices","id":"measure_power","type":"number","title":{"en":"Power","nl":"Energie"},"units":{"en":"W"},"desc":{"en":"Power in Watt (W)","nl":"Vermogen in Watt (W)"},"chartType":"stepLine","decimals":2,"getable":true,"setable":false},"meter_power":{"uri":"homey:manager:devices","id":"meter_power","type":"number","title":{"en":"Power Meter","nl":"Energiemeter"},"decimals":2,"units":{"en":"KWh"},"chartType":"spline","desc":{"en":"Power usage in KiloWattHour (kWh)","nl":"Stroomverbuik in KiloWattUur (kWh)"},"getable":true,"setable":false}},"capabilitiesArray":["onoff","measure_power","meter_power"],"capabilitiesOptions":{"onoff":{},"measure_power":{},"meter_power":{}},"flags":["zwave"],"mobile":{"components":[{"id":"icon","capabilities":["onoff"]},{"id":"sensor","capabilities":["meter_power","measure_power"]},{"id":"toggle","capabilities":["onoff"]}]},"order":17,"online":true,"state":{"onoff":false,"measure_power":0,"meter_power":36.38},"lastUpdated":{"onoff":"2018-03-07T13:53:03.

**Comment by sprut666666** [comment]
use 1.5.1

**Comment by Patrikgolfer** [comment]
Thanx for that quickfix now everything seems to work :)
