### ISSUE TITLE
Homey gets non responsive after installing 1.51

### ISSUE THREAD

**Issue by Patrikgolfer** [sprut666666/com.sprut.homekit#16]
Cant reach my Homey after installing HomeKit 1.51. Works after PTP but only works for for 1hour . I have to repower homey twice after installing lastet HomeKit 1.51 .this has never happend before so I suspect that the latest update is the reason

**Comment by sprut666666** [comment]
Please describe the problem in more detail

**Comment by Patrikgolfer** [comment]
After installing 1,51 Homey worked for an hour then it went offline. Repower of homey get it going again homekit worked for an hour or maybe 2 . Then it went offline .Could not log in to homey through homeys app. in homekit all devices was offline. Repower again then disabled homekit app and now it runs perfect.
Hard to now the cause when homey gets offline ..Tried to log in directly to homeys ip adress with my browswer and the page failed to load completly and I waited 3 min. I suspect its running 100% cpu but thats just a guess

**Comment by sprut666666** [comment]
Is everything OK now ?

**Comment by Patrikgolfer** [comment]
Now when i disabled homekit my homey has been on line seens yesterday evening. I can try to enable it now again and se it the problem comes back

**Comment by sprut666666** [comment]
How many devices do you use and what firmware do you have on Homey?

**Comment by Patrikgolfer** [comment]
1.57 and about 25-30 devices Z-wave and 433mhz

**Comment by Patrikgolfer** [comment]
Reinstalled the homekit app added all my devices .Worked for 30 min now i get no answer from all devices in Apples homekit app. In the log from Homys Homekit app  everything looks fine. Even i HomeCenter app on my apple TV its the same. Non responding HomeCenter app

**Comment by Patrikgolfer** [comment]
Reebooted and update Homey to 1.58 still no connection with homecenter or Home app on my IPhone

**Comment by PeterEIER** [comment]
also using 1.5.1 and Homey Firmware 1.5.8, this issue does not affect me however. Home app works on iPhone and iPad, also Eve is working fine. Controlling Hue lamps and an Airconditioner thru Homekit.

**Comment by sprut666666** [comment]
@Patrikgolfer Very strange. Tell us what equipment you use?
@PeterEIER I also do not have problems with the update ...

**Comment by Patrikgolfer** [comment]
Hi 
I maybe found what caused the issue. It has run with no problem for 5 hours now. What I did was I completely removed all my devices and removed my home from my iPhone and iPad . I think that an older setup was left on my home app on my iPad and it was some sort of conflict what made HomeKit on homey to lose connection. Now it seems to work . But it’s just a theory that it was that how caused the problem .  I let you now if the problem persist 
/ Thanks for your will to helping 
Best regards/ Patrik

**Comment by Patrikgolfer** [comment]
Runs Great now
