### ISSUE TITLE
IOS 11.1 Beta 2 show no answer Homey

### ISSUE THREAD

**Issue by Sillec123** [sprut666666/com.sprut.homekit#2]
I am using:

ATV4 with last beta
Iphone 6S IOS 11.1 Beta 2
Ipad Pro IOS 11.1 Beta 2

The Homey Bridge in Homeykit is showing: No answer
The Plugin is running and the log looks well in homey.

**Comment by sprut666666** [comment]
I'm not responsible for the HomeyKit plugin, In my plugin HomeKit everything works fine on ios11.X last beta & tvos11.X last beta - Checked repeatedly)

**Comment by Sillec123** [comment]
I reinstalled the app and now i am not possible to pair it again:

The code 666 66 666 isn't working anymore. Wrong code!

**Comment by sprut666666** [comment]
Remove the house, restart the iPhone - remove the plugin and then install it. + https://support.apple.com/en-us/HT204893

**Comment by sprut666666** [comment]
How are you ?
