### ISSUE TITLE
App Crash - mdns-server.js

### ISSUE THREAD

**Issue by Veldkornet** [sprut666666/com.sprut.homekit#6]
Never had a problem with the app, but last night in the middle of the night it crashed 3x in a row with the following, v1.2.2:

![7de0f297-38ac-40c4-82c8-43faedc516f1](https://user-images.githubusercontent.com/10297361/33196620-a7fc113c-d0e0-11e7-9093-ef10b9f1f846.jpeg)

**Comment by Veldkornet** [comment]
I should mention that my WAN had an outage around the same time. Although weird that it would affect this.

**Comment by sprut666666** [comment]
Please update with Github or wait until they approve the update;)

**Comment by Veldkornet** [comment]
Thanks, it’s updated. Although I don’t know how to replicate the issue, so I guess we’ll just assume that it’s fixed for now ;)

FYI, my devices are in a “Not Responding” state more recently than they were in the past. A restart of the app seems to resolve the issue. Not sure if it’s maybe from all the Node.js updates?
