### ISSUE TITLE
Creating scenes/automation fails with too many devices

### ISSUE THREAD

**Issue by skandshus** [sprut666666/com.sprut.homekit#7]
Ive seen issues in creating scenes. for example.

"when everybody leaves home".. turn off all lights.. if i choose 3 light to turn off. everything works. if i then choose all my lightning at home which is right now 10 ... Then it will fail and randomly turn off 5-7 lights Then i have to manually launch the automation for the rest of the light's to turn off.
The same thing happens the other way around when arriving home and wanting to have 10 lights turn on. 5-7 turns on, and i have to manually launch the automation scene once again to get the remaining lights turned on.. if i pick only 3 lights to turn on. They it works everytime... 

It makes me believe there might be a limit on how many devices can be used at the same time for the homekit to "complete" the task..

**Comment by sprut666666** [comment]
There are no restrictions
