### ISSUE TITLE
[Error] Lamp: Error: Homey Offline

### ISSUE THREAD

**Issue by Veldkornet** [sprut666666/com.sprut.homekit#9]
So every few days, the devices stop responding from within HomeKit on my phone (devices connected via a different bridge, like My Philips Hue work fine). 

The devices can still be turned on and off via the Homey app. 

If I go to the HomeKit log on Homey, I see an entry such as the below every time I try to turn a device off and on from Home app on my phone:

[Error] Tafellamp: Error: Homey Offline

However other devices, like my Fibaro motion sensor, do still show up in the log as reporting information. 

After restarting the HomeKit app on Homey, everything works again. 

It appears as though the HomeKit app still communicates with the devices properly, but just stops accepting the commands from the Home app on my phone.

**Comment by Blusser** [comment]
I got this issue as well (homekit V1.4.0) and homey 1.5.6-rc.8
It seems to be that communication from homey to homekit is working fine, but from homekit to homey is broken ?

**Comment by Veldkornet** [comment]
Any news? Happens like Every two days...

![391a6db5-0fbf-4864-870a-744f7552a4bd](https://user-images.githubusercontent.com/10297361/35644232-b1342122-06c8-11e8-837a-6f6a5a89c187.png)

**Comment by mvunen** [comment]
Any progress?
even with 1.5.6-rc.13 the results are the same, very often within a day every device of Homey in Homekit is offline. Do you have an idea or direction what causes this issue? 
Thanks! 
When its working I enjoy the app big time!!

**Comment by sprut666666** [comment]
Should be fixed in 1.5.0
